with-expecter: true
boilerplate-file: ".mockery_boilerplate_text.txt"
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
resolve-type-alias: False
issue-845-fix: True

packages:
  github.com/mercuryqa/rocket-lab/inventory/internal/service:
    config:
      include-regex: ".*Service"

  github.com/mercuryqa/rocket-lab/inventory/internal/repository:
    config:
      include-regex: ".*Repository"

  github.com/mercuryqa/rocket-lab/order/internal/service:
    config:
      include-regex: ".*Service"

  github.com/mercuryqa/rocket-lab/order/internal/repository:
    config:
      include-regex: ".*Repository"

  github.com/mercuryqa/rocket-lab/order/internal/client/grpc:
    config:
      include-regex: ".*Client"

  github.com/mercuryqa/rocket-lab/payment/internal/service:
    config:
      include-regex: ".*Service"

  github.com/mercuryqa/rocket-lab/payment/internal/repository:
    config:
      include-regex: ".*Repository"
