// Code generated for Rocket-lab
// © Rocket-lab 2025.
// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	model "github.com/mercuryqa/rocket-lab/order/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

type OrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderRepository) EXPECT() *OrderRepository_Expecter {
	return &OrderRepository_Expecter{mock: &_m.Mock}
}

// CancelOrder provides a mock function with given fields: id, status
func (_m *OrderRepository) CancelOrder(id string, status model.OrderStatus) bool {
	ret := _m.Called(id, status)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, model.OrderStatus) bool); ok {
		r0 = rf(id, status)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// OrderRepository_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type OrderRepository_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - id string
//   - status model.OrderStatus
func (_e *OrderRepository_Expecter) CancelOrder(id interface{}, status interface{}) *OrderRepository_CancelOrder_Call {
	return &OrderRepository_CancelOrder_Call{Call: _e.mock.On("CancelOrder", id, status)}
}

func (_c *OrderRepository_CancelOrder_Call) Run(run func(id string, status model.OrderStatus)) *OrderRepository_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(model.OrderStatus))
	})
	return _c
}

func (_c *OrderRepository_CancelOrder_Call) Return(_a0 bool) *OrderRepository_CancelOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepository_CancelOrder_Call) RunAndReturn(run func(string, model.OrderStatus) bool) *OrderRepository_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function with given fields: order
func (_m *OrderRepository) CreateOrder(order *model.Order) error {
	ret := _m.Called(order)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Order) error); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderRepository_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type OrderRepository_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - order *model.Order
func (_e *OrderRepository_Expecter) CreateOrder(order interface{}) *OrderRepository_CreateOrder_Call {
	return &OrderRepository_CreateOrder_Call{Call: _e.mock.On("CreateOrder", order)}
}

func (_c *OrderRepository_CreateOrder_Call) Run(run func(order *model.Order)) *OrderRepository_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Order))
	})
	return _c
}

func (_c *OrderRepository_CreateOrder_Call) Return(_a0 error) *OrderRepository_CreateOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepository_CreateOrder_Call) RunAndReturn(run func(*model.Order) error) *OrderRepository_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function with given fields: id
func (_m *OrderRepository) GetOrder(id string) (*model.Order, bool) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *model.Order
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (*model.Order, bool)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *model.Order); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// OrderRepository_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type OrderRepository_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - id string
func (_e *OrderRepository_Expecter) GetOrder(id interface{}) *OrderRepository_GetOrder_Call {
	return &OrderRepository_GetOrder_Call{Call: _e.mock.On("GetOrder", id)}
}

func (_c *OrderRepository_GetOrder_Call) Run(run func(id string)) *OrderRepository_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *OrderRepository_GetOrder_Call) Return(_a0 *model.Order, _a1 bool) *OrderRepository_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_GetOrder_Call) RunAndReturn(run func(string) (*model.Order, bool)) *OrderRepository_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// PayOrder provides a mock function with given fields: id, status
func (_m *OrderRepository) PayOrder(id string, status model.OrderStatus) bool {
	ret := _m.Called(id, status)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, model.OrderStatus) bool); ok {
		r0 = rf(id, status)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// OrderRepository_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type OrderRepository_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - id string
//   - status model.OrderStatus
func (_e *OrderRepository_Expecter) PayOrder(id interface{}, status interface{}) *OrderRepository_PayOrder_Call {
	return &OrderRepository_PayOrder_Call{Call: _e.mock.On("PayOrder", id, status)}
}

func (_c *OrderRepository_PayOrder_Call) Run(run func(id string, status model.OrderStatus)) *OrderRepository_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(model.OrderStatus))
	})
	return _c
}

func (_c *OrderRepository_PayOrder_Call) Return(_a0 bool) *OrderRepository_PayOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepository_PayOrder_Call) RunAndReturn(run func(string, model.OrderStatus) bool) *OrderRepository_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrder provides a mock function with given fields: id, paymentMethod, transactionUuid
func (_m *OrderRepository) UpdateOrder(id string, paymentMethod model.PaymentMethod, transactionUuid string) bool {
	ret := _m.Called(id, paymentMethod, transactionUuid)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrder")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, model.PaymentMethod, string) bool); ok {
		r0 = rf(id, paymentMethod, transactionUuid)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// OrderRepository_UpdateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrder'
type OrderRepository_UpdateOrder_Call struct {
	*mock.Call
}

// UpdateOrder is a helper method to define mock.On call
//   - id string
//   - paymentMethod model.PaymentMethod
//   - transactionUuid string
func (_e *OrderRepository_Expecter) UpdateOrder(id interface{}, paymentMethod interface{}, transactionUuid interface{}) *OrderRepository_UpdateOrder_Call {
	return &OrderRepository_UpdateOrder_Call{Call: _e.mock.On("UpdateOrder", id, paymentMethod, transactionUuid)}
}

func (_c *OrderRepository_UpdateOrder_Call) Run(run func(id string, paymentMethod model.PaymentMethod, transactionUuid string)) *OrderRepository_UpdateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(model.PaymentMethod), args[2].(string))
	})
	return _c
}

func (_c *OrderRepository_UpdateOrder_Call) Return(_a0 bool) *OrderRepository_UpdateOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepository_UpdateOrder_Call) RunAndReturn(run func(string, model.PaymentMethod, string) bool) *OrderRepository_UpdateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
