// Code generated for Rocket-lab
// © Rocket-lab 2025.
// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/mercuryqa/rocket-lab/order/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

type OrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderService) EXPECT() *OrderService_Expecter {
	return &OrderService_Expecter{mock: &_m.Mock}
}

// CancelOrder provides a mock function with given fields: id, status
func (_m *OrderService) CancelOrder(id string, status model.OrderStatus) bool {
	ret := _m.Called(id, status)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, model.OrderStatus) bool); ok {
		r0 = rf(id, status)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// OrderService_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type OrderService_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - id string
//   - status model.OrderStatus
func (_e *OrderService_Expecter) CancelOrder(id interface{}, status interface{}) *OrderService_CancelOrder_Call {
	return &OrderService_CancelOrder_Call{Call: _e.mock.On("CancelOrder", id, status)}
}

func (_c *OrderService_CancelOrder_Call) Run(run func(id string, status model.OrderStatus)) *OrderService_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(model.OrderStatus))
	})
	return _c
}

func (_c *OrderService_CancelOrder_Call) Return(_a0 bool) *OrderService_CancelOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderService_CancelOrder_Call) RunAndReturn(run func(string, model.OrderStatus) bool) *OrderService_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function with given fields: ctx, order
func (_m *OrderService) CreateOrder(ctx context.Context, order *model.OrderRequest) (*model.OrderResponse, error) {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *model.OrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.OrderRequest) (*model.OrderResponse, error)); ok {
		return rf(ctx, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.OrderRequest) *model.OrderResponse); ok {
		r0 = rf(ctx, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.OrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.OrderRequest) error); ok {
		r1 = rf(ctx, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type OrderService_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order *model.OrderRequest
func (_e *OrderService_Expecter) CreateOrder(ctx interface{}, order interface{}) *OrderService_CreateOrder_Call {
	return &OrderService_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, order)}
}

func (_c *OrderService_CreateOrder_Call) Run(run func(ctx context.Context, order *model.OrderRequest)) *OrderService_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.OrderRequest))
	})
	return _c
}

func (_c *OrderService_CreateOrder_Call) Return(_a0 *model.OrderResponse, _a1 error) *OrderService_CreateOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_CreateOrder_Call) RunAndReturn(run func(context.Context, *model.OrderRequest) (*model.OrderResponse, error)) *OrderService_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function with given fields: id
func (_m *OrderService) GetOrder(id string) (*model.Order, bool) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *model.Order
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (*model.Order, bool)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *model.Order); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// OrderService_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type OrderService_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - id string
func (_e *OrderService_Expecter) GetOrder(id interface{}) *OrderService_GetOrder_Call {
	return &OrderService_GetOrder_Call{Call: _e.mock.On("GetOrder", id)}
}

func (_c *OrderService_GetOrder_Call) Run(run func(id string)) *OrderService_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *OrderService_GetOrder_Call) Return(_a0 *model.Order, _a1 bool) *OrderService_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_GetOrder_Call) RunAndReturn(run func(string) (*model.Order, bool)) *OrderService_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// PayOrder provides a mock function with given fields: id, paymentMethod
func (_m *OrderService) PayOrder(id string, paymentMethod model.PaymentMethod) string {
	ret := _m.Called(id, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string, model.PaymentMethod) string); ok {
		r0 = rf(id, paymentMethod)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// OrderService_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type OrderService_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - id string
//   - paymentMethod model.PaymentMethod
func (_e *OrderService_Expecter) PayOrder(id interface{}, paymentMethod interface{}) *OrderService_PayOrder_Call {
	return &OrderService_PayOrder_Call{Call: _e.mock.On("PayOrder", id, paymentMethod)}
}

func (_c *OrderService_PayOrder_Call) Run(run func(id string, paymentMethod model.PaymentMethod)) *OrderService_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(model.PaymentMethod))
	})
	return _c
}

func (_c *OrderService_PayOrder_Call) Return(_a0 string) *OrderService_PayOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderService_PayOrder_Call) RunAndReturn(run func(string, model.PaymentMethod) string) *OrderService_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrder provides a mock function with given fields: id, paymentMethod, transactionUuid
func (_m *OrderService) UpdateOrder(id string, paymentMethod model.PaymentMethod, transactionUuid string) bool {
	ret := _m.Called(id, paymentMethod, transactionUuid)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrder")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, model.PaymentMethod, string) bool); ok {
		r0 = rf(id, paymentMethod, transactionUuid)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// OrderService_UpdateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrder'
type OrderService_UpdateOrder_Call struct {
	*mock.Call
}

// UpdateOrder is a helper method to define mock.On call
//   - id string
//   - paymentMethod model.PaymentMethod
//   - transactionUuid string
func (_e *OrderService_Expecter) UpdateOrder(id interface{}, paymentMethod interface{}, transactionUuid interface{}) *OrderService_UpdateOrder_Call {
	return &OrderService_UpdateOrder_Call{Call: _e.mock.On("UpdateOrder", id, paymentMethod, transactionUuid)}
}

func (_c *OrderService_UpdateOrder_Call) Run(run func(id string, paymentMethod model.PaymentMethod, transactionUuid string)) *OrderService_UpdateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(model.PaymentMethod), args[2].(string))
	})
	return _c
}

func (_c *OrderService_UpdateOrder_Call) Return(_a0 bool) *OrderService_UpdateOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderService_UpdateOrder_Call) RunAndReturn(run func(string, model.PaymentMethod, string) bool) *OrderService_UpdateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
