// Code generated for Rocket-lab
// © Rocket-lab 2025.
// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/mercuryqa/rocket-lab/order/model"
	mock "github.com/stretchr/testify/mock"
)

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

type OrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderService) EXPECT() *OrderService_Expecter {
	return &OrderService_Expecter{mock: &_m.Mock}
}

// CancelOrder provides a mock function with given fields: ctx, id, status
func (_m *OrderService) CancelOrder(ctx context.Context, id string, status string) bool {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// OrderService_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type OrderService_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - status string
func (_e *OrderService_Expecter) CancelOrder(ctx interface{}, id interface{}, status interface{}) *OrderService_CancelOrder_Call {
	return &OrderService_CancelOrder_Call{Call: _e.mock.On("CancelOrder", ctx, id, status)}
}

func (_c *OrderService_CancelOrder_Call) Run(run func(ctx context.Context, id string, status string)) *OrderService_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *OrderService_CancelOrder_Call) Return(_a0 bool) *OrderService_CancelOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderService_CancelOrder_Call) RunAndReturn(run func(context.Context, string, string) bool) *OrderService_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CheckItems provides a mock function with given fields: ctx, ids
func (_m *OrderService) CheckItems(ctx context.Context, ids []string) bool {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for CheckItems")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, []string) bool); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// OrderService_CheckItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckItems'
type OrderService_CheckItems_Call struct {
	*mock.Call
}

// CheckItems is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *OrderService_Expecter) CheckItems(ctx interface{}, ids interface{}) *OrderService_CheckItems_Call {
	return &OrderService_CheckItems_Call{Call: _e.mock.On("CheckItems", ctx, ids)}
}

func (_c *OrderService_CheckItems_Call) Run(run func(ctx context.Context, ids []string)) *OrderService_CheckItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *OrderService_CheckItems_Call) Return(_a0 bool) *OrderService_CheckItems_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderService_CheckItems_Call) RunAndReturn(run func(context.Context, []string) bool) *OrderService_CheckItems_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function with given fields: ctx, order
func (_m *OrderService) CreateOrder(ctx context.Context, order *model.GetOrderResponse) error {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.GetOrderResponse) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderService_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type OrderService_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order *model.GetOrderResponse
func (_e *OrderService_Expecter) CreateOrder(ctx interface{}, order interface{}) *OrderService_CreateOrder_Call {
	return &OrderService_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, order)}
}

func (_c *OrderService_CreateOrder_Call) Run(run func(ctx context.Context, order *model.GetOrderResponse)) *OrderService_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.GetOrderResponse))
	})
	return _c
}

func (_c *OrderService_CreateOrder_Call) Return(_a0 error) *OrderService_CreateOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderService_CreateOrder_Call) RunAndReturn(run func(context.Context, *model.GetOrderResponse) error) *OrderService_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function with given fields: ctx, id
func (_m *OrderService) GetOrder(ctx context.Context, id string) (*model.GetOrderResponse, bool) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *model.GetOrderResponse
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.GetOrderResponse, bool)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.GetOrderResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.GetOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// OrderService_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type OrderService_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *OrderService_Expecter) GetOrder(ctx interface{}, id interface{}) *OrderService_GetOrder_Call {
	return &OrderService_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, id)}
}

func (_c *OrderService_GetOrder_Call) Run(run func(ctx context.Context, id string)) *OrderService_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderService_GetOrder_Call) Return(_a0 *model.GetOrderResponse, _a1 bool) *OrderService_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_GetOrder_Call) RunAndReturn(run func(context.Context, string) (*model.GetOrderResponse, bool)) *OrderService_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// PayOrder provides a mock function with given fields: ctx, id, status, paymentMethodName, transactionUuid
func (_m *OrderService) PayOrder(ctx context.Context, id string, status string, paymentMethodName string, transactionUuid string) bool {
	ret := _m.Called(ctx, id, status, paymentMethodName, transactionUuid)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) bool); ok {
		r0 = rf(ctx, id, status, paymentMethodName, transactionUuid)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// OrderService_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type OrderService_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - status string
//   - paymentMethodName string
//   - transactionUuid string
func (_e *OrderService_Expecter) PayOrder(ctx interface{}, id interface{}, status interface{}, paymentMethodName interface{}, transactionUuid interface{}) *OrderService_PayOrder_Call {
	return &OrderService_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, id, status, paymentMethodName, transactionUuid)}
}

func (_c *OrderService_PayOrder_Call) Run(run func(ctx context.Context, id string, status string, paymentMethodName string, transactionUuid string)) *OrderService_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *OrderService_PayOrder_Call) Return(_a0 bool) *OrderService_PayOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderService_PayOrder_Call) RunAndReturn(run func(context.Context, string, string, string, string) bool) *OrderService_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
